# Generated by Django 4.0 on 2022-01-08 14:40

from django.db import migrations


def populate_initial_languages(apps, schema_editor):
    initial_languages = [
        ('ro', 'Română'),
        ('el', 'Ελληνικὰ'),
        ('ar', 'العربية'),
        ('en', 'English'),
    ]

    Language = apps.get_model('collection', 'Language')
    languages = []
    for code, name in initial_languages:
        languages.append(Language(code=code, name=name))

    db_alias = schema_editor.connection.alias
    Language.objects.using(db_alias).bulk_create(languages)


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_language_translation_field_alter_author_members_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_initial_languages),
    ]
