# Generated by Django 4.0 on 2022-01-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collection', '0004_populate_default_group_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='lang',
            field=models.ForeignKey(default='ro', on_delete=django.db.models.deletion.PROTECT, to='collection.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicaltext',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='original_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'collection'), ('model', 'language')), models.Q(('app_label', 'collection'), ('model', 'author')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('lang', 'original_id', 'field')},
        ),
    ]
